# ScriptBlockPlus v${project.version} Config #

## ===== 自動アップデートの設定 ===== ##
# [true -> 有効 | false -> 無効]
# メッセージはOPにしか表示されません。

# 最新バージョンを確認するかどうか。
UpdateChecker: true

# 最新のプラグインをダウンロードするかどうか。
AutoDownload: true

# ダウンロードした更新内容を、メモ帳で開くかどうか。
OpenChangeLog: true


## ===== コンソールの設定 ===== ##
# [true -> 有効 | false -> 無効]
# 言語ファイルの console が対象です。
# コンソールログを表示するかどうか。
ConsoleLog: false


## ===== 左クリックの設定 ===== ##
# [true -> 有効 | false -> 無効]
# 左クリックでもスクリプトを実行するかどうか。
LeftClick: true


## ===== 左クリック判定の設定 ===== ##
# アドベンチャーモードの左クリックの判定の長さの設定
# ※強引に再現してるため、Minecraft本来の判定とは異なります。
LeftArmLength: 5.22
