name: ${project.name}
main: com.github.yuttyann.scriptblockplus.ScriptBlock
version: ${project.version}
description: ${project.description}
author: yuttyann44581
website: https://github.com/yuttyann/ScriptBlockPlus
softdepend: [ScriptBlock, Vault, WorldEdit, PlaceholderAPI]

commands:
  scriptblockplus:
    description: ScriptBlockPlus コマンド
    usage: |
           /<command> tool - 実行者にスクリプト編集ツールを配布します。
           /<command> reload - 全てのファイルの再読み込みを行います。
           /<command> checkver - 最新のプラグインが存在するかチェックします。
           /<command> datamigr - ScriptBlockのスクリプトをPlusに移行します。
           /<command> <scripttype> create <options> - ブロックにスクリプトを設定します。
           /<command> <scripttype> add <options> - ブロックにスクリプトを追加します。
           /<command> <scripttype> remove - ブロックのスクリプトを削除します。
           /<command> <scripttype> view - ブロックのスクリプトを表示します。
           /<command> worldedit paste <pasteonair> [overwrite] - 選択範囲にスクリプトをペーストします。
           /<command> worldedit remove - 選択範囲のスクリプトを削除します。
    aliases: [sbp]

permissions:
  scriptblockplus.*:
    default: op
    children:
      scriptblockplus.command.tool: true
      scriptblockplus.command.reload: true
      scriptblockplus.command.checkver: true
      scriptblockplus.command.datamigr: true
      scriptblockplus.command.interact: true
      scriptblockplus.command.break: true
      scriptblockplus.command.walk: true
      scriptblockplus.command.worldedit: true
      scriptblockplus.interact.use: true
      scriptblockplus.break.use: true
      scriptblockplus.walk.use: true
      scriptblockplus.tool.scripteditor: true
  scriptblockplus.command.tool:
    default: op
  scriptblockplus.command.reload:
    default: op
  scriptblockplus.command.checkver:
    default: op
  scriptblockplus.command.datamigr:
    default: op
  scriptblockplus.command.interact:
    default: op
  scriptblockplus.command.walk:
    default: op
  scriptblockplus.command.worldedit:
    default: op
  scriptblockplus.interact.use:
    default: true
  scriptblockplus.break.use:
    default: true
  scriptblockplus.walk.use:
    default: true
  scriptblockplus.tool.scripteditor:
    default: op